### ISSUE TITLE
🚀 Feature: Add Github Issue Bot for Node.js (TypeScript) 

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/templates#147]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement the Github Issue Bot function in Node.js (TypeScript). You can look at the existing [Appwrite Functions Templates](https://github.com/appwrite/templates) in another coding language.

Your function should behave and be implemented similarly to existing Github Issue Bot Node.js template.

### Tasks summary:

- [ ] Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ] Create a branch `feat-implement-github-issue-bot-node-typescript`
- [ ] Write code for the function in folder `node-typescript/github-issue-bot/`. 
- [ ] Test the function using Appwrite, **provide a video**.
- [ ] Write a `README.md` explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/github-issue-bot).
- [ ] Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by lyqht** [comment]
Hello there, can i check that the requirement of issue is to create a Typescript version of the existing repo here https://github.com/appwrite/templates/tree/main/node/github-issue-bot

If so, can I get assigned to this issue? thank you!

**Comment by Haimantika** [comment]
> Hello there, can i check that the requirement of issue is to create a Typescript version of the existing repo here https://github.com/appwrite/templates/tree/main/node/github-issue-bot
> 
> If so, can I get assigned to this issue? thank you!

Yes! You are right! 

Have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:
1. Please update us with your progress every 3 days, so that we know that you are working on it.
2. Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Akshaybagai52** [comment]
If he is unable to complete it then you can assign this issue to me
Thanks

**Comment by Haimantika** [comment]
Hi @lyqht due to inactivity from your end, assigning the issue to @Akshaybagai52

**Comment by Akshaybagai52** [comment]
Thanks @Haimantika for assigning this issue to me. Will update you about the progress

**Comment by vimode** [comment]
Hey @Akshaybagai52 are you still working on this? If not, I would like to take a stab at this. 

Thank you.

**Comment by vimode** [comment]
@Haimantika If this issue opens up, I would really like to be work on this as I would like to contribute to other similar TS template issues as they open up. Thank you.

**Comment by Haimantika** [comment]
Hi @Akshaybagai52 do you have an update? Anything about your progress/queries will help us know that you are still working on it.

**Comment by drraghavendra** [comment]
Hi @christyjacob4 @tessamero please assign the issue to me.

**Comment by Akshaybagai52** [comment]
Hi @Haimantika 
Sorry for delay but due to time issue I'm not able to complete this issue you can assign to anyone.
Thanks

**Comment by drraghavendra** [comment]
> Hi @Haimantika @christyjacob4 @tessamero please assign the issue to me.

please reply me asap

**Comment by Haimantika** [comment]
> Hi @Haimantika @christyjacob4 @tessamero please assign the issue to me.

Hi, we are assigning issues on a first-come, first-serve basis. You are next in-line if @vimode drops :)
