### ISSUE TITLE
🚀 Feature: Add Github Issue Bot for Java 

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/templates#157]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement the Github Issue Bot function in Java. You can look at the existing [Appwrite Functions Templates](https://github.com/appwrite/templates) in another coding language.

Your function should behave and be implemented similarly to existing Github Issue Bot Node.js template.

### Tasks summary:

- [ ] Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ] Create a branch `feat-implement-github-issue-bot-java`
- [ ] Write code for the function in folder `java/github-issue-bot/`. 
- [ ] Test the function using Appwrite, **provide a video**.
- [ ] Write a `README.md` explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/github-issue-bot).
- [ ] Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by idanela** [comment]
Can you assign the issue to me?

**Comment by Haimantika** [comment]
> Can you assign the issue to me?

I am using this message to assign issues:

Hi @idanela  have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:
1. Please update us with your progress every 3 days, so that we know that you are working on it.
2. Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by idanela** [comment]
Hi, 
I Wanted to asked if you want the bot to respond also for reopening an issue?
If so would you like it to be handled differently?

**Comment by loks0n** [comment]
> Hi, I Wanted to asked if you want the bot to respond also for reopening an issue? If so would you like it to be handled differently?

Let's match the functionality of the existing `node/github-issue-bot` template 👍

**Comment by idanela** [comment]
OK, Thanks 👍

**Comment by idanela** [comment]
Update:
Currently I'm pretty much done with the code and now I trying to test it using appwrite using self hosting.

**Comment by idanela** [comment]
Updae:
I have a problem with deploying java application with dependencies.
I tried self-hosting my own instace of Appwrite , and couldn't manged to deploy it because of the dependecies.
First I tried to use maven and the following commands : apt-get update && apt-get maven %% mvn clean install got a bunch of errors  such as :E: Unable to locate package maven, sh: 1: mvn: not found etc.
Later I tried to change it to gradle and encountered a problem with the size of the file:
✗ Error The file size is either not valid or exceeds the maximum allowed size. Please check the file or the value of the _APP_STORAGE_LIMIT environment variable.
I feel I stuck and I'll be happy to get some help from one of the team.

**Comment by Haimantika** [comment]
> Updae: I have a problem with deploying java application with dependencies. I tried self-hosting my own instace of Appwrite , and couldn't manged to deploy it because of the dependecies. First I tried to use maven and the following commands : apt-get update && apt-get maven %% mvn clean install got a bunch of errors such as :E: Unable to locate package maven, sh: 1: mvn: not found etc. Later I tried to change it to gradle and encountered a problem with the size of the file: ✗ Error The file size is either not valid or exceeds the maximum allowed size. Please check the file or the value of the _APP_STORAGE_LIMIT environment variable. I feel I stuck and I'll be happy to get some help from one of the team.

Hi, request you to ask your queries in the Discord server - https://appwrite.io/discord

**Comment by idanela** [comment]
Hi,
I'm from Israel and currently we have a - delixated situation in the country.
I wanted to update you about that and ask if I can have more time to finish the issue?

**Comment by gewenyu99** [comment]
> Hi, I'm from Israel and currently we have a - delicate situation in the country. I wanted to update you about that and ask if I can have more time to finish the issue?

Yeah, take as long as you need!

Take care, we understand the situation.

**Comment by tessamero** [comment]
@idanela I'm very sorry for the situation going on and completely understand. I'm currently closing all inactive hacktoberfest related issues, if you'd like, I'm happy to keep this open for longer. I'll remove the hacktoberfest label for now.

**Comment by idanela** [comment]
I live in Israel and currently I was recruited by the army.
For now I'm not working on it

**Comment by tessamero** [comment]
@idanela Thank you for your service to your country, I will keep the issue open.
