### ISSUE TITLE
🚀 Feature: Add Subscriptions with Stripe for Swift 

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/templates#185]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement the Subscriptions with Stripe function in Swift. You can look at the existing [Appwrite Functions Templates](https://github.com/appwrite/templates) in another coding language.

Your function should behave and be implemented similarly to existing Subscriptions with Stripe Node.js template.

### Tasks summary:

- [ ] Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ] Create a branch `feat-implement-subscriptions-with-stripe-swift`
- [ ] Write code for the function in folder `swift/subscriptions-with-stripe/`. 
- [ ] Test the function using Appwrite, **provide a video**.
- [ ] Write a `README.md` explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/subscriptions-with-stripe).
- [ ] Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by Haimantika** [comment]
> Can you assign me this issue please?

Hi @Vinz000 have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Vinz000** [comment]
@gewenyu99 I need further clarification, I noticed the implementation of this template using node.js calls the Stripe api. However, I can't call the Stripe api directly using swift so I'm unsure how to achieve the same functionality?

**Comment by Vinz000** [comment]
@gewenyu99 I see. Will work on this now!

**Comment by Vinz000** [comment]
Still working

**Comment by ShamanthOP** [comment]
Hey @Haimantika Can you assign this issue to me?

**Comment by Haimantika** [comment]
Hi @Vinz000 are you still working on it? If you have any updates, let us know.

**Comment by Vinz000** [comment]
@Haimantika I'm no longer working on it

**Comment by Haimantika** [comment]
> Hey @Haimantika Can you assign this issue to me?

Hi @ShamanthOP the issue is yours now. Remember to keep us updated every 3 days.

**Comment by ShamanthOP** [comment]
Hey @Haimantika I won't be able to complete this due to some personal constraints.

**Comment by Nupoor10** [comment]
Hello @Haimantika, Can I take this up?

**Comment by nishchay-veer** [comment]
Hi @Haimantika . I've worked with Stripe API and would love  to work on this issue. Can you please assign this to me ?

**Comment by tessamero** [comment]
Closing issue due to inactivity and hacktoberfest being over, thank you for taking the time to be part of hacktoberfest this year :)
