### ISSUE TITLE
🚀 Feature: Add Sync with Meilisearch for C++ 

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/templates#187]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement the Sync with Meilisearch function in C++. You can look at the existing [Appwrite Functions Templates](https://github.com/appwrite/templates) in another coding language.

Your function should behave and be implemented similarly to existing Sync with Meilisearch Node.js template.

### Tasks summary:

- [ ] Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ] Create a branch `feat-implement-sync-with-meilisearch-cpp`
- [ ] Write code for the function in folder `cpp/sync-with-meilisearch/`. 
- [ ] Test the function using Appwrite, **provide a video**.
- [ ] Write a `README.md` explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/sync-with-meilisearch).
- [ ] Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by knshkp** [comment]
i want to work on this issue could you assign this issue to me please

**Comment by loks0n** [comment]
Hi @knshkp, I've assigned the issue to you! Happy Hacktoberfest 🎃!

Notes:
- Please update us with your progress every 3 days, so that we know you are working on it.
- Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Amit12234** [comment]
Hi , if it get unassigned , please assign me.

**Comment by shahjugal** [comment]
Hi, if it gets unassigned please assign me later

**Comment by Haimantika** [comment]
Hi @knshkp due to inactivity from your end, I am reassigning the issue to the next person. @Amit12234 the issue is yours now

**Comment by Amit12234** [comment]
Hi @Haimantika thank you , I have started gathering information and working on the issue.

**Comment by knshkp** [comment]
Sorry @Haimantika  Actually i got hospitalised due to viral so i didn't work on that

**Comment by Haimantika** [comment]
> Sorry @Haimantika Actually i got hospitalised due to viral so i didn't work on that

Sorry for that, please take care :(

**Comment by Haimantika** [comment]
> Hi @Haimantika thank you , I have started gathering information and working on the issue.

Hi, is there an update? It has been 4 days, will have to reassign the issue to the next person due to inactivity from your end.

**Comment by Amit12234** [comment]
Hi , so sorry, will not be able to complete it , you can assign it to someone else, I have my exams starting from tomorrow.

**Comment by gewenyu99** [comment]
@Amit12234 if you're still actively working on it, that's fine! We're just checking for updates :D

**Comment by Amit12234** [comment]
Actually, there is a lot of code that needs to be written, I am trying my best but due to my exam starting from today I won't be able to focus on the issue and will not be able to complete it.

**Comment by gewenyu99** [comment]
@Amit12234 I will assign it to the next person.

@shahjugal if you're still interested, the issue is yours

**Comment by Anurag-space** [comment]
Hey @Haimantika 
could you assign me this issue.
