### ISSUE TITLE
🚀 Feature: Add Sync with Meilisearch for .NET 

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/templates#190]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement the Sync with Meilisearch function in .NET. You can look at the existing [Appwrite Functions Templates](https://github.com/appwrite/templates) in another coding language.

Your function should behave and be implemented similarly to existing Sync with Meilisearch Node.js template.

### Tasks summary:

- [ ] Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ] Create a branch `feat-implement-sync-with-meilisearch-dotnet`
- [ ] Write code for the function in folder `dotnet/sync-with-meilisearch/`. 
- [ ] Test the function using Appwrite, **provide a video**.
- [ ] Write a `README.md` explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/sync-with-meilisearch).
- [ ] Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by Rishank23** [comment]
I would like to work on this

**Comment by Rishank23** [comment]
I would like to work on this. 
Can you help me with the setup as well? I didn't understand about RuntimeContext and RuntimeOutput

**Comment by rbhagavathsingh** [comment]
I would like to contribute one this. however I do not see .NET runtime in the Functions runtime either in cloud or locally.

**Comment by loks0n** [comment]
Hi @Rishank23, I've assigned the issue to you! Happy Hacktoberfest 🎃!

Notes:
- Please update us with your progress every 3 days, so that we know you are working on it.
- Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

The RuntimeContext and RuntimeOutput objects are added by OpenRuntimes. They contain the methods necessary to read and respond to HTTP requests. Be sure to join us on Discord if you have more questions, we can better support you there :)

**Comment by loks0n** [comment]
> I would like to contribute one this. however I do not see .NET runtime in the Functions runtime either in cloud or locally.

Sorry, we are operating on first-come first-serve basis. Be sure to check out our other open issues to see if any are available!

**Comment by Haimantika** [comment]
Hi @Rishank23 unassigning the issue due to inactivity. @rbhagavathsingh the issue is yours now

**Comment by parthj000** [comment]
hi @Haimantika @loks0n 
 , i would wish to work on this , please assign it to me

**Comment by ShatilKhan** [comment]
I'd like to work on this

**Comment by rbhagavathsingh** [comment]
@Haimantika Please reassign to either @parthj000  or @ShatilKhan , I wont be able to complete this soon.

**Comment by Haimantika** [comment]
> hi @Haimantika @loks0n , i would wish to work on this , please assign it to me

Hi @parthj000 assigning the issue to you. Please update us every 3 days :)

**Comment by Haimantika** [comment]
Hi @parthj000 are you still working on it? If not, we will be reassigning the issue to the next contributor

**Comment by tessamero** [comment]
Closing issue due to inactivity and hacktoberfest being over, thank you for taking the time to be part of hacktoberfest this year :)
