### ISSUE TITLE
🚀 Feature: Add Sync with Meilisearch for Java 

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/templates#191]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement the Sync with Meilisearch function in Java. You can look at the existing [Appwrite Functions Templates](https://github.com/appwrite/templates) in another coding language.

Your function should behave and be implemented similarly to existing Sync with Meilisearch Node.js template.

### Tasks summary:

- [ ] Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ] Create a branch `feat-implement-sync-with-meilisearch-java`
- [ ] Write code for the function in folder `java/sync-with-meilisearch/`. 
- [ ] Test the function using Appwrite, **provide a video**.
- [ ] Write a `README.md` explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/sync-with-meilisearch).
- [ ] Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by GLADI8R** [comment]
Hi, I would like to work on this issue.

**Comment by tessamero** [comment]
hi @GLADI8R  , you've been assigned to the issue. You may start working on it. :-) Please keep us updated every 3 days so we know you are still working on it, so the issue doesn't get reassigned :)

happy coding 😃

**Comment by Bijit-Mondal** [comment]
If it is not done, please assign me to this

**Comment by Haimantika** [comment]
> If it is not done, please assign me to this

Hi, we assign issues on first-come first-serve basis, if we do not have an update from Danish, we will assign it to you!

**Comment by GLADI8R** [comment]
Hi, I'm still working on this issue.
Update till now: understood the appwrite console, CLiI, and the nodejs code. 
Stuck setting up the Java-17 environment in CLI. Included runtime of java-17.0 in .env of appwrite but java option is not visible during `appwrite init function`.

**Comment by GLADI8R** [comment]
Update till now: Working on the code right now and resolving the build errors.

**Comment by FelixFelicis555** [comment]
Assign the issue  to me if the issue didn't get sorted or either of them didn't respond

**Comment by GLADI8R** [comment]
Hi @Haimantika @gewenyu99, I've been stuck on getting documents list. Have posted this on support channel on discord, but no replies from anyone on how to fix it. What should I do?

**Comment by gewenyu99** [comment]
@GLADI8R What's the issue with document list?

**Comment by GLADI8R** [comment]
I followed the kotlin sdk docs and on using the function `databases.listDocuments({params})`, the error says no such function as `listDocuments()`. 
Using kotlin-sdk v4.0.0 on self-hosted appwrite cli v4.1.0

**Comment by gewenyu99** [comment]
Can I see your code?

**Comment by GLADI8R** [comment]
```package io.openruntimes.java.src;

import com.meilisearch.sdk.Config;
import com.meilisearch.sdk.Index;

import io.openruntimes.java.RuntimeContext;
import io.openruntimes.java.RuntimeOutput;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Arrays;

import java.nio.file.Files;
import java.nio.file.Path;

import io.appwrite.Client;
import io.appwrite.services.Databases;
import io.appwrite.Query;
import io.appwrite.models.DocumentList;
import io.appwrite.models.Document;


public class Main {
    String[] envStrings = {
            "APPWRITE_API_KEY",
            "APPWRITE_DATABASE_ID",
            "APPWRITE_COLLECTION_ID",
            "MEILISEARCH_ENDPOINT",
            "MEILISEARCH_INDEX_NAME",
            "MEILISEARCH_ADMIN_API_KEY",
            "MEILISEARCH_SEARCH_API_KEY"
    };
    List<String> envList = Arrays.asList(envStrings);

    final String regex = "\\{\\{([^\\}]+)\\}\\}";

    private void throwIfMissing(Map<String, String> env) throws Exception {
        List<String> missing = new ArrayList<>();

        for(String e: envList) {
            if (!env.containsKey(e) || env.get(e).isEmpty()) {
                missing.add(e);
            }
        }

        if (missing.size() > 0) {
            throw new Exception("Missing values in .env");
        }
    }

    private String interpolate(String template, Map<String, String> vars) {
        for(String key: vars.keySet()) {
            template = template.replaceAll("\\{\\{([^\\}]+)\\}\\}", vars.get(key));
        }

        return template;
    }

    private String getStaticFile(String filename) {
        return Files.readString(Path.of(filename));
    }

    /**
     * @param context
     * @return
     * @throws Exception
     */
    public RuntimeOutput main(RuntimeContext context) throws Exception {

        throwIfMissing(System.getenv());

        if (context.getReq().getMethod().equals("GET")) {
            Map<String, String> conf = new HashMap<String, String> ();
            conf.put("MEILISEARCH_ENDPOINT", System.getenv("MEILISEARCH_ENDPOINT"));
            conf.put("MEILISEARCH_INDEX_NAME", System.getenv("MEILISEARCH_INDEX_NAME"));
            conf.put("MEILISEARCH_SEARCH_API_KEY", System.getenv("MEILISEARCH_SEARCH_API_KEY"));

            String html = interpolate(getStaticFile("index.html"), conf);

            Map<String, String> headers = new HashMap<String, String> ();
            headers.put("Content-Type", "text/html; charset=utf-8");

            return context.getRes().send(html, 200, headers);
        }

        Client client = new Client();
        client
                .setEndpoint(System.getenv("APPWRITE_ENDPOINT").toString())
                .setProject(System.getenv("APPWRITE_FUNCTION_PROJECT_ID").toString())
                .setKey(System.getenv("APPWRITE_API_KEY").toString());

        Databases databases = new Databases(client);

        // meilisearch client
        Config meilisearchConfig = new Config(
                System.getenv("MEILISEARCH_ENDPOINT").toString(),
                System.getenv("MEILISEARCH_ADMIN_API_KEY").toString()
        );
        com.meilisearch.sdk.Client meilisearch = new com.meilisearch.sdk.Client(meilisearchConfig);

        Index index = meilisearch.index(System.getenv("MEILISEARCH_INDEX_NAME"));

        String cursor = null;

        do {
            List<String> queries = new ArrayList<String>();

            if(cursor != null && queries.size()<100) {
                queries.add(cursor);
            }

            List<Document<Map<String, Object>>> documents = databases.listDocuments(
                    System.getenv("APPWRITE_DATABASE_ID").toString(),
                    System.getenv("APPWRITE_COLLECTION_ID").toString(),
                    queries
            ).toMap().get("documents");

            if(documents.size() > 0) {
                cursor = documents.get(documents.size() - 1).id.toString();
            } else {
                context.log("No more documents found.");
                cursor = null;
                break;
            }

            context.log("Syncing chunk of " + documents.size() + " documents ...");
            index.addDocuments(documents.toString(), "id");

        } while(cursor != null);

        return context.getRes().send("Sync finished", 200);
    }
}
```

**Comment by gewenyu99** [comment]
I can't reproduce this problem @GLADI8R, how are you deploying the function, what are your build commands?

**Comment by GLADI8R** [comment]
I'm using self-hosted appwrite cli. I did `appwrite deploy function` and the build logs show that no method `listDocuments`. 
The parameters and imports are same as mentioned in sdk-for-kotlin.

**Comment by gewenyu99** [comment]
@GLADI8R what build commands did you configure to install Appwrite as a dependency in the function?

**Comment by GLADI8R** [comment]
generated the starter function using `appwrite init project` then the function.
Inside deps.gradle, I have: 
```
dependencies {
    implementation 'io.appwrite:sdk-for-kotlin:4.0.0'
    implementation 'com.meilisearch.sdk:meilisearch-java:0.11.2'
}
```

**Comment by gewenyu99** [comment]
> generated the starter function using `appwrite init project` then the function. Inside deps.gradle, I have:
> 
> ```
> dependencies {
>     implementation 'io.appwrite:sdk-for-kotlin:4.0.0'
>     implementation 'com.meilisearch.sdk:meilisearch-java:0.11.2'
> }
> ```

Can I see the build commands you configured in your Appwrite Console?

**Comment by gewenyu99** [comment]
<img width="1468" alt="Screenshot 2023-10-11 at 3 46 47 PM" src="https://github.com/appwrite/templates/assets/29069505/50eb8b84-d49d-4d68-b531-e423084074aa">

**Comment by GLADI8R** [comment]
No commands are displayed and I haven't used any build commands. Just deployed the function...

**Comment by gewenyu99** [comment]
@GLADI8R In that case, no dependencies, including the Appwrite SDK is installed. Remember to run a install command for which ever dependency manager you're using!

**Comment by GLADI8R** [comment]
I don't think I need any build commands because the dependencies are already in `deps.gradle` file and on deploying the function, gradle runs perfectly. The only issue is that the relevant class methods are not recognized

**Comment by loks0n** [comment]
> No commands are displayed and I haven't used any build commands. Just deployed the function...

What version of Appwrite are you using?

Does the starter function work for you?

> I don't think I need any build commands because the dependencies are already in `deps.gradle` file and on deploying the function, gradle runs perfectly. The only issue is that the relevant class methods are not recognized. method signature here: https://github.com/appwrite/sdk-for-kotlin/blob/main/src/main/kotlin/io/appwrite/services/Databases.kt

What's wrong with the method signature?

**Comment by GLADI8R** [comment]
Using appwrite v1.4.3. I made changes in the starter template generated in `appwrite init function`. 
When using `databases.listDocuments()`, logs show method not applicable.

![image](https://github.com/appwrite/templates/assets/69247129/980c0160-6003-41e3-a3ba-31ba42d4bb7b)

**Comment by Haimantika** [comment]
> Using appwrite v1.4.3. I made changes in the starter template generated in `appwrite init function`. When using `databases.listDocuments()`, logs show method not applicable.
> 
> ![image](https://user-images.githubusercontent.com/69247129/274642567-980c0160-6003-41e3-a3ba-31ba42d4bb7b.png)

Hi, if you are still stuck in this, would request you to open a support thread in our [Discord server](https://appwrite.io/docs)

**Comment by loks0n** [comment]
Did you find a solution for this?

**Comment by tessamero** [comment]
Closing issue due to inactivity and hacktoberfest being over, thank you for taking the time to be part of hacktoberfest this year :)
