### ISSUE TITLE
🚀 Feature: Add Sync with Meilisearch for Kotlin 

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/templates#192]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement the Sync with Meilisearch function in Kotlin. You can look at the existing [Appwrite Functions Templates](https://github.com/appwrite/templates) in another coding language.

Your function should behave and be implemented similarly to existing Sync with Meilisearch Node.js template.

### Tasks summary:

- [ ] Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ] Create a branch `feat-implement-sync-with-meilisearch-kotlin`
- [ ] Write code for the function in folder `kotlin/sync-with-meilisearch/`. 
- [ ] Test the function using Appwrite, **provide a video**.
- [ ] Write a `README.md` explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/sync-with-meilisearch).
- [ ] Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by mohith2883** [comment]
Hey @gewenyu99 can u assign me

**Comment by loks0n** [comment]
Awesome! I have assigned you @mohith2883 🥳 

Notes:
- Please update us with your progress every 3 days, so that we know that you are working on it.
- Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Haimantika** [comment]
Hi @mohith2883 is there any update?

**Comment by ShamanthOP** [comment]
Hey @Haimantika I'd like to take this up. Can you assign this to me

**Comment by Haimantika** [comment]
Hi @mohith2883 unassigning the issue due to inactivity. @ShamanthOP the issue is yours now, please update every 3 days

**Comment by Haimantika** [comment]
Hi @ShamanthOP is there an update? We will have to unassign the issue from you due to inactivity

**Comment by ShamanthOP** [comment]
Hey I'm having trouble serving static files ... Hope to resolve it soon

**Comment by gewenyu99** [comment]
> Hey I'm having trouble serving static files ... Hope to resolve it soon

What static files do you need to serve?

**Comment by ShamanthOP** [comment]
@gewenyu99 HTML file. [🔗](https://discord.com/channels/564160730845151244/1161705248428130384)

**Comment by gewenyu99** [comment]
Ohhh coool, @ShamanthOP can I see your code?

**Comment by ShamanthOP** [comment]
Hey @gewenyu99 Check this out #234

**Comment by gewenyu99** [comment]
@ShamanthOP I don't see anything obviously wrong. How about this, try these steps and see where it fails:

1. Return a plain response
2. Return a "<h1>HELLOOOOO</h1>" string as HTML
3. Return a static HTML without the Util functions.
4. Use your util functions.

I'm wondering where the problem might lie, lmk!

**Comment by ShamanthOP** [comment]
Hey @gewenyu99 the current code in #234 is working fine. The problem is that I'm not able to read the HTML file from say  ```static/index.html``` ([support post](https://discord.com/channels/564160730845151244/1161705248428130384))

**Comment by gewenyu99** [comment]
> Hey @gewenyu99 the current code in #234 is working fine. The problem is that I'm not able to read the HTML file from say `static/index.html` ([support post](https://discord.com/channels/564160730845151244/1161705248428130384))

Ahhh I see. @ShamanthOP The root directory isn't going to be relative from your code folder because your function is invoked from a runtime that treats it as a dependency. So the root level directory is going to be different. 

Is there a way to normalize paths? Maybe try this, print the path of `./` and experiment with where your paths are based from. 

https://stackoverflow.com/questions/64171104/how-to-get-the-current-working-directory-in-kotlin

**Comment by gewenyu99** [comment]
also @ShamanthOP try joining office hours, we can debug together live :P

**Comment by ShamanthOP** [comment]
> also @ShamanthOP try joining office hours, we can debug together live :P

Sure. I'll experiment with this and I'll let you know⚡
