### ISSUE TITLE
🚀 Feature: Add Sync with Meilisearch for Node.js (TypeScript) 

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/templates#193]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement the Sync with Meilisearch function in Node.js (TypeScript). You can look at the existing [Appwrite Functions Templates](https://github.com/appwrite/templates) in another coding language.

Your function should behave and be implemented similarly to existing Sync with Meilisearch Node.js template.

### Tasks summary:

- [ ] Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ] Create a branch `feat-implement-sync-with-meilisearch-node-typescript`
- [ ] Write code for the function in folder `node-typescript/sync-with-meilisearch/`. 
- [ ] Test the function using Appwrite, **provide a video**.
- [ ] Write a `README.md` explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/sync-with-meilisearch).
- [ ] Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by AvaterClasher** [comment]
Can i be Assigned this ?
Thank You

**Comment by loks0n** [comment]
Hi @AvaterClasher, I've assigned this issue to you! Thanks your interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:
- Please update us with your progress every 3 days, so that we know that you are working on it.
- Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by omzi** [comment]
If AvatarClasher is not interested in it, kindly reassign it to me.

**Comment by Haimantika** [comment]
Closing this as it has been solved https://github.com/appwrite/templates/pull/211
