### ISSUE TITLE
🚀 Feature: Add Sync with Meilisearch for PHP 

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/templates#194]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement the Sync with Meilisearch function in PHP. You can look at the existing [Appwrite Functions Templates](https://github.com/appwrite/templates) in another coding language.

Your function should behave and be implemented similarly to existing Sync with Meilisearch Node.js template.

### Tasks summary:

- [ ] Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ] Create a branch `feat-implement-sync-with-meilisearch-php`
- [ ] Write code for the function in folder `php/sync-with-meilisearch/`. 
- [ ] Test the function using Appwrite, **provide a video**.
- [ ] Write a `README.md` explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/sync-with-meilisearch).
- [ ] Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by Harsh3341** [comment]
Hey @gewenyu99 I wanted to work on this issue

**Comment by gewenyu99** [comment]
> Hey @gewenyu99 I wanted to work on this issue

It's yours! Happy hacktoberfest.

Remember to comeback every 2-3 days with an update, and lmk if you need anyhelp!

**Comment by Harsh3341** [comment]
> > I wanted to work on this issue
> 
> Hi, @monhelnog we are assigning issues on a first-come, first-serve basis, if @Harsh3341 decides to drop off, we will assign it to you.

I have gone through the existing function template to understand how it will be built in PHP, I will start working on this issue from today onward.

**Comment by Harsh3341** [comment]
Readme will also contain video?

**Comment by Haimantika** [comment]
> Readme will also contain video?

Add it in your PR

**Comment by Harsh3341** [comment]
@gewenyu99 @Haimantika is there any documentation from Appwrite on how to run https://github.com/appwrite/templates/tree/main/php/sync-with-algolia ? As I'm new to PHP and have setup everything, but facing difficulties in starting the project, I have previously worked on nodejs

**Comment by gewenyu99** [comment]
@Harsh3341 The template will have a wizard that guides you through setting up the template in Appwrite 
<img width="1710" alt="Screenshot 2023-10-05 at 9 41 45 AM" src="https://github.com/appwrite/templates/assets/29069505/d3b172d5-9aa7-45be-add7-01c545073dc9">

**Comment by FelixFelicis555** [comment]
If the issue still didn't get sorted please assign the issue to me ?

**Comment by Haimantika** [comment]
> If the issue still didn't get sorted please assign the issue to me ?

This issue already has a PR made :)

**Comment by FelixFelicis555** [comment]
@Haimantika Why haven’t you closed the issue yet If he made a PR

**Comment by Haimantika** [comment]
> @Haimantika Why haven’t you closed the issue yet If he made a PR

We are yet to review it, and reviewing can take upto 15 days :)

**Comment by gewenyu99** [comment]
Closed by https://github.com/appwrite/templates/pull/222

**Comment by Harsh3341** [comment]
Discord Username - .harshgupta
