### ISSUE TITLE
🚀 Feature: Add Sync with Meilisearch for Python 

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/templates#195]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement the Sync with Meilisearch function in Python. You can look at the existing [Appwrite Functions Templates](https://github.com/appwrite/templates) in another coding language.

Your function should behave and be implemented similarly to existing Sync with Meilisearch Node.js template.

### Tasks summary:

- [ ] Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ] Create a branch `feat-implement-sync-with-meilisearch-python`
- [ ] Write code for the function in folder `python/sync_with_meilisearch/`. 
- [ ] Test the function using Appwrite, **provide a video**.
- [ ] Write a `README.md` explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/sync-with-meilisearch).
- [ ] Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by ishandutta0098** [comment]
Hi @gewenyu99 I would like to contribute to this issue, please assign the issue to me.

**Comment by Haimantika** [comment]
> Hi @gewenyu99 I would like to contribute to this issue, please assign the issue to me.

Hi @ishandutta0098 have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:
1. Please update us with your progress every 3 days, so that we know that you are working on it.
2. Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Ln11211** [comment]
I can work on this if the assignee cannot.

**Comment by mohith2883** [comment]
Hey @Haimantika can you kindly reassign it to me if anyone is not interested

**Comment by ishandutta0098** [comment]
Update - @Haimantika  I have written the code, figuring out the testing part. To test it I am supposed to create a function and run it successfully right or can I raise a PR first and we can discuss the code before testing?

**Comment by gewenyu99** [comment]
@ishandutta0098 yep, deploy on Appwrite cloud and test your code :)

**Comment by Tejpratap14** [comment]
I want to give this issue a try. Can u assign the task to me?

**Comment by Haimantika** [comment]
> I want to give this issue a try. Can u assign the task to me?

Hi, Ishan is working on it, if he gets idle, we can assign it to you :)

**Comment by ishandutta0098** [comment]
@Haimantika @gewenyu99 I have updated the PR message with a successful demo video and it is ready for review.

**Comment by Haimantika** [comment]
> @Haimantika @gewenyu99 I have updated the PR message with a successful demo video and it is ready for review.

Thanks, I have requested a review from @loks0n :)

**Comment by ishandutta0098** [comment]
Thanks Haimantika!

**Comment by Shunux-Stuxnet** [comment]
Assign this issue to me

**Comment by gewenyu99** [comment]
Closed by https://github.com/appwrite/templates/pull/218
