### ISSUE TITLE
🚀 Feature: Add Sync with Meilisearch for Swift 

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/templates#197]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement the Sync with Meilisearch function in Swift. You can look at the existing [Appwrite Functions Templates](https://github.com/appwrite/templates) in another coding language.

Your function should behave and be implemented similarly to existing Sync with Meilisearch Node.js template.

### Tasks summary:

- [ ] Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ] Create a branch `feat-implement-sync-with-meilisearch-swift`
- [ ] Write code for the function in folder `swift/sync-with-meilisearch/`. 
- [ ] Test the function using Appwrite, **provide a video**.
- [ ] Write a `README.md` explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/sync-with-meilisearch).
- [ ] Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by Bijit-Mondal** [comment]
Assign this to me please

**Comment by gewenyu99** [comment]
@Bijit-Mondal It's yours!

Remember to come back every 2-3 days with an update, lmk if you need any help.

Happy hacking!

**Comment by Bijit-Mondal** [comment]
`Swift version 5.6 (swift-5.6-RELEASE)
Target: x86_64-unknown-linux-gnu`
 this is my swift version , when I am trying to run
 `swift build`
 I am getting the following error
 `/home/bijit/Desktop/templates/swift/starter/.build/checkouts/swift-log/Sources/Logging/Logging.swift:1392:64: error: value of optional type 'UnsafeMutablePointer<tm>?' must be unwrapped to a value of type 'UnsafeMutablePointer<tm>'`
 
 how to resolve it, should I use Swift 5.5

**Comment by Bijit-Mondal** [comment]
Using 5.5 didn't work also

**Comment by Haimantika** [comment]
> unable to deploy the simple starter function in swift on appwrite. getting error
> 
> ```
> [817/918] Compiling NIOPosix BSDSocketAPICommon.swift
> remark: Incremental compilation has been disabled: it is not compatible with whole module optimization[819/920] Compiling NIO Exports.swift
> remark: Incremental compilation has been disabled: it is not compatible with whole module optimizationremark: Incremental compilation has been disabled: it is not compatible with whole module optimization[821/923] Compiling NIOTLS ApplicationProtocolNegotiationHandler.swift
> remark: Incremental compilation has been disabled: it is not compatible with whole module optimization[823/925] Compiling NIOSOCKS SOCKSClientHandler.swift
> remark: Incremental compilation has been disabled: it is not compatible with whole module optimization[825/927] Compiling NIOHTTP1 ByteCollectionUtils.swift
> remark: Incremental compilation has been disabled: it is not compatible with whole module optimization[827/929] Compiling NIOSSL ByteBufferBIO.swift
> remark: Incremental compilation has been disabled: it is not compatible with whole module optimization[829/931] Compiling NIOWebSocket Base64.swift
> remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
> ```

Hi, did you ask about this in our Discord server?

**Comment by Bijit-Mondal** [comment]
Yes, but no one responded

**Comment by gewenyu99** [comment]
@Bijit-Mondal 

> unable to deploy the simple starter function in swift on appwrite. getting error
> 
> ```
> [817/918] Compiling NIOPosix BSDSocketAPICommon.swift
> remark: Incremental compilation has been disabled: it is not compatible with whole module optimization[819/920] Compiling NIO Exports.swift
> remark: Incremental compilation has been disabled: it is not compatible with whole module optimizationremark: Incremental compilation has been disabled: it is not compatible with whole module optimization[821/923] Compiling NIOTLS ApplicationProtocolNegotiationHandler.swift
> remark: Incremental compilation has been disabled: it is not compatible with whole module optimization[823/925] Compiling NIOSOCKS SOCKSClientHandler.swift
> remark: Incremental compilation has been disabled: it is not compatible with whole module optimization[825/927] Compiling NIOHTTP1 ByteCollectionUtils.swift
> remark: Incremental compilation has been disabled: it is not compatible with whole module optimization[827/929] Compiling NIOSSL ByteBufferBIO.swift
> remark: Incremental compilation has been disabled: it is not compatible with whole module optimization[829/931] Compiling NIOWebSocket Base64.swift
> remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
> ```

But these are't errors, looks like your build just timed out.

**Comment by Bijit-Mondal** [comment]
It is happening everytime I am going to build, anyway to resolve

**Comment by Bijit-Mondal** [comment]
@Haimantika help me out , I am stuck.

**Comment by Bijit-Mondal** [comment]
Getting error
```
Could not resolve host: appwrite-executor with status code 0
```

**Comment by Bijit-Mondal** [comment]
```
_APP_FUNCTIONS_TIMEOUT=6000
_APP_FUNCTIONS_BUILD_TIMEOUT=6000
```

I have increased the function build timeout, but still the build is failed

any ways to resolve it?

**Comment by Haimantika** [comment]
> ```
> _APP_FUNCTIONS_TIMEOUT=6000
> _APP_FUNCTIONS_BUILD_TIMEOUT=6000
> ```
> 
> I have increased the function build timeout, but still the build is failed
> 
> After this line in logs build is failing `[793/918] Compiling p_hkdf.c`
> 
> any ways to resolve it?

Hi, please ask your queries on our support channel in [Discord](https://appwrite.io/discord)

**Comment by gewenyu99** [comment]
@Bijit-Mondal Can I see your code with instructions to reproduce?

**Comment by Bijit-Mondal** [comment]
I was trying to run the starter template only

**Comment by gewenyu99** [comment]
> I was trying to run the starter template only

From CLI or template?

**Comment by gewenyu99** [comment]
> ```
> _APP_FUNCTIONS_TIMEOUT=6000
> _APP_FUNCTIONS_BUILD_TIMEOUT=6000
> ```
> 
> I have increased the function build timeout, but still the build is failed
> 
> After this line in logs build is failing `[793/918] Compiling p_hkdf.c`
> 
> any ways to resolve it?

This might not be long enough actually. Can you try a longer time?

**Comment by Bijit-Mondal** [comment]
From Template, 


yeah I have also increased the time still having issue

**Comment by tessamero** [comment]
Closing issue due to inactivity and hacktoberfest being over, thank you for taking the time to be part of hacktoberfest this year :)
