### ISSUE TITLE
🚀 Feature: Add WhatsApp with Vonage for Bun 

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/templates#198]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement the WhatsApp with Vonage function in Bun. You can look at the existing [Appwrite Functions Templates](https://github.com/appwrite/templates) in another coding language.

Your function should behave and be implemented similarly to existing WhatsApp with Vonage Node.js template.

### Tasks summary:

- [ ] Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ] Create a branch `feat-implement-whatsapp-with-vonage-bun`
- [ ] Write code for the function in folder `bun/whatsapp-with-vonage/`. 
- [ ] Test the function using Appwrite, **provide a video**.
- [ ] Write a `README.md` explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/whatsapp-with-vonage).
- [ ] Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by PrerakMathur20** [comment]
Hey Can I work on this?

**Comment by loks0n** [comment]
Hi @PrerakMathur20, I've assigned the issue to you! Happy Hacktoberfest 🎃!

Notes:
- Please update us with your progress every 3 days, so that we know you are working on it.
- Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by heyhimansh** [comment]
@loks0n I would like to work on this Issue.

**Comment by Haimantika** [comment]
Hi @PrerakMathur20 due to inactivity from your end, I will have to unassign the issue from you. @heyhimansh I have already assigned one issue to you, would you like to work on it too?

**Comment by heyhimansh** [comment]
@Haimantika  Thank you for the update. I'd like to first complete the assigned issue before proceeding with the new one.

**Comment by parthj000** [comment]
hi @Haimantika  i am interested to work on it , please assign it to me :)

**Comment by Haimantika** [comment]
> hi @Haimantika, @loks0n i am interested to work on it , please assign it to me :)

The issue is assigned to you. Please remember to give us updates every 3 days!

**Comment by parthj000** [comment]
thank you !!

**Comment by FelixFelicis555** [comment]
Please assign the issue to me if there's inactivity ?

**Comment by parthj000** [comment]
update: i am almost complete with my research work and looking forward to implement it.

**Comment by Haimantika** [comment]
> update: i am almost complete with my research work and looking forward to implement it.

Feel free to reach out to us on [Discord](https://appwrite.io./discord) if you need any help.

**Comment by parthj000** [comment]
sure , i will !

**Comment by parthj000** [comment]
update: i m almost done ,just resolving some issues !

**Comment by Haimantika** [comment]
> update: i m almost done ,just resolving some issues !

If you have any questions, reach out to us on [Discord](https://appwrite.io/discord)

**Comment by parthj000** [comment]
ok .

**Comment by parthj000** [comment]
update:i have resolved the issues and i will raise pr soon.

**Comment by parthj000** [comment]
sorry , actually i was busy with my exams , i will raise it 
today.

**Comment by parthj000** [comment]
hey @Haimantika @loks0n ,
I have raised a PR, please review it 
https://github.com/appwrite/templates/pull/252

**Comment by parthj000** [comment]
pARTh my discord name !
