### ISSUE TITLE
🚀 Feature: Add WhatsApp with Vonage for C++ 

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/templates#199]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement the WhatsApp with Vonage function in C++. You can look at the existing [Appwrite Functions Templates](https://github.com/appwrite/templates) in another coding language.

Your function should behave and be implemented similarly to existing WhatsApp with Vonage Node.js template.

### Tasks summary:

- [ ] Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ] Create a branch `feat-implement-whatsapp-with-vonage-cpp`
- [ ] Write code for the function in folder `cpp/whatsapp-with-vonage/`. 
- [ ] Test the function using Appwrite, **provide a video**.
- [ ] Write a `README.md` explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/whatsapp-with-vonage).
- [ ] Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by FreSauce** [comment]
Hey @gewenyu99, Can you assign me this issue?

**Comment by dhaneshragu** [comment]
I would like to work on this. Can u pls assign this to me? @gewenyu99

**Comment by Haimantika** [comment]
> Hey @gewenyu99, Can you assign me this issue?

Hi @FreSauce have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:
1. Please update us with your progress every 3 days, so that we know that you are working on it.
2. Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Haimantika** [comment]
> I would like to work on this. Can u pls assign this to me? @gewenyu99

Hi, we assign issues on first-come first-serve basis. If @FreSauce is unresponsive, we will assign it to you.

**Comment by heyhimansh** [comment]
@Haimantika I would like to work on this Issue.

**Comment by Haimantika** [comment]
> @Haimantika I would like to work on this Issue.

Hi, we assign issues on first-come first-serve basis. If @FreSauce is unresponsive, we will assign it to you.

**Comment by Haimantika** [comment]
@FreSauce is there any update?

**Comment by FreSauce** [comment]
@Haimantika, Yea I'm halfway through. Done with the curl request, just need to write code to send static files and throw error

**Comment by Haimantika** [comment]
Hi @FreSauce let us know when your PR is ready for review.

**Comment by tessamero** [comment]
Closing issue due to inactivity and hacktoberfest being over, thank you for taking the time to be part of hacktoberfest this year :)
