### ISSUE TITLE
🚀 Feature: Add WhatsApp with Vonage for Dart 

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/templates#200]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement the WhatsApp with Vonage function in Dart. You can look at the existing [Appwrite Functions Templates](https://github.com/appwrite/templates) in another coding language.

Your function should behave and be implemented similarly to existing WhatsApp with Vonage Node.js template.

### Tasks summary:

- [ ] Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ] Create a branch `feat-implement-whatsapp-with-vonage-dart`
- [ ] Write code for the function in folder `dart/whatsapp_with_vonage/`. 
- [ ] Test the function using Appwrite, **provide a video**.
- [ ] Write a `README.md` explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/whatsapp-with-vonage).
- [ ] Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by tejas-raskar** [comment]
I would like to work on this. Can you assign it to me?

**Comment by loks0n** [comment]
Hi @tejas-raskar , I've assigned the issue to you! Happy Hacktoberfest 🎃!

Notes:
- Please update us with your progress every 3 days, so that we know you are working on it.
- Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by nimsmgr** [comment]
I would like to work on this if it gets unassigned.

**Comment by tejas-raskar** [comment]
Hey @loks0n
 
**Quick Update:** I am still working on the issue. Will be done by the weekend.

**Comment by tejas-raskar** [comment]
![image](https://github.com/appwrite/templates/assets/118300989/c79e347b-e8bb-43b0-b7df-81828d6e1fad)

When I call this function to get the index.html file after a 'GET' request I get the following error:

FileSystemException: Cannot open file, path = '/usr/local/server/src/function/../static/index.html' (OS Error: No such file or directory, errno = 2)

What am I doing wrong?

**Comment by letsintegreat** [comment]
Hey, I would like to be assigned if the current assignee is unresponsive, thanks!

**Comment by Haimantika** [comment]
> > > ![image](https://user-images.githubusercontent.com/118300989/273306414-c79e347b-e8bb-43b0-b7df-81828d6e1fad.png)
> > > When I call this function to get the index.html file after a 'GET' request I get the following error:
> > > FileSystemException: Cannot open file, path = '/usr/local/server/src/function/../static/index.html' (OS Error: No such file or directory, errno = 2)
> > > What am I doing wrong? @loks0n @gewenyu99
> > 
> > 
> > Seems like the `..` is not expanding, you may need to use path.normalize function
> 
> Okay! I will be continuing working on this issue

Hi, do you have an update? Are you still working on it?

**Comment by tejas-raskar** [comment]
> > > > ![image](https://user-images.githubusercontent.com/118300989/273306414-c79e347b-e8bb-43b0-b7df-81828d6e1fad.png)
> > > > When I call this function to get the index.html file after a 'GET' request I get the following error:
> > > > FileSystemException: Cannot open file, path = '/usr/local/server/src/function/../static/index.html' (OS Error: No such file or directory, errno = 2)
> > > > What am I doing wrong? @loks0n @gewenyu99
> > > 
> > > 
> > > Seems like the `..` is not expanding, you may need to use path.normalize function
> > 
> > Okay! I will be continuing working on this issue
> 
> Hi, do you have an update? Are you still working on it?

Hi, Yes I'm still working on it. The implementation is almost ready and I'm currently fixing some bugs.

**Comment by gewenyu99** [comment]
Cloised by #246
