### ISSUE TITLE
🚀 Feature: Add WhatsApp with Vonage for .NET 

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/templates#202]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement the WhatsApp with Vonage function in .NET. You can look at the existing [Appwrite Functions Templates](https://github.com/appwrite/templates) in another coding language.

Your function should behave and be implemented similarly to existing WhatsApp with Vonage Node.js template.

### Tasks summary:

- [ ] Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ] Create a branch `feat-implement-whatsapp-with-vonage-dotnet`
- [ ] Write code for the function in folder `dotnet/whatsapp-with-vonage/`. 
- [ ] Test the function using Appwrite, **provide a video**.
- [ ] Write a `README.md` explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/whatsapp-with-vonage).
- [ ] Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by gauravagrwal** [comment]
Hi @gewenyu99, I would like to work on this, can you please assign it to me...

**Comment by loks0n** [comment]
Hi @gauravagrwal, I've assigned the issue to you! Happy Hacktoberfest 🎃!

Notes:
- Please update us with your progress every 3 days, so that we know you are working on it.
- Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by heyhimansh** [comment]
Hey @loks0n , i would like to work on this issue.

**Comment by Haimantika** [comment]
Hi @gauravagrwal reassigning the issue to the next person due to inactivity from your end. @heyhimansh the issue is yours now

**Comment by Haimantika** [comment]
Hi @heyhimansh is there an update from your end? The issue will be unassigned from you tomorrow, due to inactivity

**Comment by heyhimansh** [comment]
Hi @Haimantika , yes, I've tried extensively, but I haven't been able to resolve the error. I kindly request that you assign this issue to someone else. I apologize for any inconvenience.

**Comment by PalaniappanC** [comment]
Can I work on this @Haimantika

**Comment by tessamero** [comment]
hi @PalaniappanC , I have assigned the issue to you. Please do update us every 3 days to ensure it doesn't get reassigned. Thank you and happy hacking :)

**Comment by PalaniappanC** [comment]
Hi @tessamero I have setup the appwrite environment. Getting issue while setting up the dotnet runtime. Will fix this issue first and then will work on the code

**Comment by Haimantika** [comment]
> Hi @tessamero I have setup the appwrite environment. Getting issue while setting up the dotnet runtime. Will fix this issue first and then will work on the code

You can always reach out to us on [Discord](https://appwrite.io/discord)

**Comment by PalaniappanC** [comment]
Hi folks I have contributed to a similar item like this. I would like to un assign myself and make way for other first time contributors like me.

**Comment by gewenyu99** [comment]
@TejasMate looks like you're next in line, assigned to you.

**Comment by tessamero** [comment]
Closing issue due to inactivity and hacktoberfest being over, thank you for taking the time to be part of hacktoberfest this year :)
