### ISSUE TITLE
🚀 Feature: Add WhatsApp with Vonage for Java 

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/templates#203]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement the WhatsApp with Vonage function in Java. You can look at the existing [Appwrite Functions Templates](https://github.com/appwrite/templates) in another coding language.

Your function should behave and be implemented similarly to existing WhatsApp with Vonage Node.js template.

### Tasks summary:

- [ ] Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ] Create a branch `feat-implement-whatsapp-with-vonage-java`
- [ ] Write code for the function in folder `java/whatsapp-with-vonage/`. 
- [ ] Test the function using Appwrite, **provide a video**.
- [ ] Write a `README.md` explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/whatsapp-with-vonage).
- [ ] Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by Jaishree2310** [comment]
@gewenyu99  Can you please assign this issue to me ?

**Comment by singodiyashubham87** [comment]
@gewenyu99 I would like to work on this issue.

**Comment by loks0n** [comment]
Hi @Jaishree2310, I've assigned this issue to you! Thanks your interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:
- Please update us with your progress every 3 days, so that we know that you are working on it.
- Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by loks0n** [comment]
> @gewenyu99 I would like to work on this issue.

Apologies @singodiyashubham87, seems you were second in line. Be sure to check out our other issues, there are a bunch up for grabs :)

**Comment by suryanshsoni120** [comment]
If the issue hasn't been resolved, I would like to work on this. Can you assign it to me?

**Comment by Haimantika** [comment]
> If the issue hasn't been resolved, I would like to work on this. Can you assign it to me?

You are third in line, if @Jaishree2310 and @singodiyashubham87 do not respond, it will go to you.

**Comment by Jaishree2310** [comment]
@Haimantika i am working on it

**Comment by FelixFelicis555** [comment]
Please assign to me if  neither of them didn't respond

**Comment by Haimantika** [comment]
> @Haimantika i am working on it

Any more updates? Been 4 days now, will be unassigning the issue from you soon due to inactivity

**Comment by Jaishree2310** [comment]
yes by today I will raise the PR

**Comment by Haimantika** [comment]
Hi @Jaishree2310 are you still working on it? You have been inactive for a while now. Will be reassigning the issue to the next person soon.

**Comment by ketanbaitule** [comment]
Hi @Haimantika , I would like to work on this issue.

**Comment by tessamero** [comment]
@Jaishree2310 are you still working on your draft PR?

**Comment by hdhaliwa** [comment]
@Haimantika I would like to contribute to this project.

**Comment by Haimantika** [comment]
Hi @hdhaliwa , looping in @stnguyen90 who can answer it better.

**Comment by hdhaliwa** [comment]
Thank you 👍

**Comment by SakkyOP** [comment]
Hi @gewenyu99 is this issue still accepting contributions?

**Comment by arcgupta148** [comment]
Hi , is this issue still accepting contributions?

**Comment by HrithikSampson** [comment]
I would like to work on this issue if available
