### ISSUE TITLE
🚀 Feature: Add WhatsApp with Vonage for Node.js (TypeScript) 

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/templates#205]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement the WhatsApp with Vonage function in Node.js (TypeScript). You can look at the existing [Appwrite Functions Templates](https://github.com/appwrite/templates) in another coding language.

Your function should behave and be implemented similarly to existing WhatsApp with Vonage Node.js template.

### Tasks summary:

- [ ] Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ] Create a branch `feat-implement-whatsapp-with-vonage-node-typescript`
- [ ] Write code for the function in folder `node-typescript/whatsapp-with-vonage/`. 
- [ ] Test the function using Appwrite, **provide a video**.
- [ ] Write a `README.md` explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/whatsapp-with-vonage).
- [ ] Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by ShamanthOP** [comment]
I would like to work on this.

**Comment by notpritam** [comment]
I would love to contribute on this..
if i am not assigned any work can you please this to me, i would to

**Comment by Haimantika** [comment]
> I would like to work on this.


Hi @ShamanthOP have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:
1. Please update us with your progress every 3 days, so that we know that you are working on it.
2. Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Haimantika** [comment]
> I would love to contribute on this..
> if i am not assigned any work can you please assign this to me.

Hi, we assign issues on first-come first-serve basis. If Shamanth decides to discontinue, we will assign it to you.

**Comment by omzi** [comment]
If they're both not interested later on, please reassign it to me.

**Comment by FelixFelicis555** [comment]
I see this issue has been assigned,but I haven't seen any activity here in a while ,Can you reassign to me?

**Comment by omzi** [comment]
His PR for this feature had already been merged ;). It is mentioned directly above your comment.
