### ISSUE TITLE
🚀 Feature: Add WhatsApp with Vonage for Python 

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/templates#207]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement the WhatsApp with Vonage function in Python. You can look at the existing [Appwrite Functions Templates](https://github.com/appwrite/templates) in another coding language.

Your function should behave and be implemented similarly to existing WhatsApp with Vonage Node.js template.

### Tasks summary:

- [ ] Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ] Create a branch `feat-implement-whatsapp-with-vonage-python`
- [ ] Write code for the function in folder `python/whatsapp_with_vonage/`. 
- [ ] Test the function using Appwrite, **provide a video**.
- [ ] Write a `README.md` explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/whatsapp-with-vonage).
- [ ] Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by probablyArth** [comment]
I'd like to work on this issue, please assign!

**Comment by Haimantika** [comment]
> I'd like to work on this issue, please assign!

I am using this message to assign issues:

Hi @probablyArth have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:
1. Please update us with your progress every 3 days, so that we know that you are working on it.
2. Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by dhaneshragu** [comment]
Can u pls assign this to me

**Comment by Haimantika** [comment]
> Can u pls assign this to me

Hi, we assign issues on first-come first-serve basis. If Arth is unresponsive, we will assign it to you.

**Comment by probablyArth** [comment]
While working on this issue I discovered that the configuration for the nodeJS `whatsapp-with-vonage` template is wrong.
The function is looking for `VONAGE_ACCOUNT_SECRET` and `VONAGE_SIGNATURE_SECRET` rather `VONAGE_API_SECRET` and `VONAGE_API_SIGNATURE_SECRET` are being prompted in the template

![image](https://github.com/appwrite/templates/assets/61962871/9392db8a-bc50-4d75-b508-b22ffaf31413)

**Comment by probablyArth** [comment]
> While working on this issue I discovered that the configuration for the nodeJS `whatsapp-with-vonage` template is wrong. The function is looking for `VONAGE_ACCOUNT_SECRET` and `VONAGE_SIGNATURE_SECRET` rather `VONAGE_API_SECRET` and `VONAGE_API_SIGNATURE_SECRET` are being prompted in the template
> 
> ![image](https://user-images.githubusercontent.com/61962871/271933817-9392db8a-bc50-4d75-b508-b22ffaf31413.png)

There seem to be more issues with it, the function is receiving the webhook payload but not responding.

**Comment by gewenyu99** [comment]
@loks0n @Meldiron 👀

**Comment by loks0n** [comment]
> While working on this issue I discovered that the configuration for the nodeJS `whatsapp-with-vonage` template is wrong. The function is looking for `VONAGE_ACCOUNT_SECRET` and `VONAGE_SIGNATURE_SECRET` rather `VONAGE_API_SECRET` and `VONAGE_API_SIGNATURE_SECRET` are being prompted in the template
> 
> ![image](https://user-images.githubusercontent.com/61962871/271933817-9392db8a-bc50-4d75-b508-b22ffaf31413.png)

This error is the expected behaviour. 
For the function to make requests to Vonage, the environment variables need to be set. There is more information acquiring the VONAGE_ACCOUNT_SECRET and the VONAGE_SIGNATURE_SECRET in the `node/whatsapp-with-vonage/README.md` folder.

**Comment by loks0n** [comment]
> > While working on this issue I discovered that the configuration for the nodeJS `whatsapp-with-vonage` template is wrong. The function is looking for `VONAGE_ACCOUNT_SECRET` and `VONAGE_SIGNATURE_SECRET` rather `VONAGE_API_SECRET` and `VONAGE_API_SIGNATURE_SECRET` are being prompted in the template
> > ![image](https://user-images.githubusercontent.com/61962871/271933817-9392db8a-bc50-4d75-b508-b22ffaf31413.png)
> 
> There seem to be more issues with it, the function is receiving the webhook payload but not responding.

This is error also caused by missing environment variables.

**Comment by loks0n** [comment]
> While working on this issue I discovered that the configuration for the nodeJS `whatsapp-with-vonage` template is wrong. The function is looking for `VONAGE_ACCOUNT_SECRET` and `VONAGE_SIGNATURE_SECRET` rather `VONAGE_API_SECRET` and `VONAGE_API_SIGNATURE_SECRET` are being prompted in the template
> 
> ![image](https://user-images.githubusercontent.com/61962871/271933817-9392db8a-bc50-4d75-b508-b22ffaf31413.png)

Good spot! This is fixed now.

> > While working on this issue I discovered that the configuration for the nodeJS `whatsapp-with-vonage` template is wrong. The function is looking for `VONAGE_ACCOUNT_SECRET` and `VONAGE_SIGNATURE_SECRET` rather `VONAGE_API_SECRET` and `VONAGE_API_SIGNATURE_SECRET` are being prompted in the template
> > ![image](https://user-images.githubusercontent.com/61962871/271933817-9392db8a-bc50-4d75-b508-b22ffaf31413.png)
> 
> There seem to be more issues with it, the function is receiving the webhook payload but not responding.

This is the same error, caused by missing env vars. Did you see something else?

**Comment by probablyArth** [comment]
> > While working on this issue I discovered that the configuration for the nodeJS `whatsapp-with-vonage` template is wrong. The function is looking for `VONAGE_ACCOUNT_SECRET` and `VONAGE_SIGNATURE_SECRET` rather `VONAGE_API_SECRET` and `VONAGE_API_SIGNATURE_SECRET` are being prompted in the template
> > ![image](https://user-images.githubusercontent.com/61962871/271933817-9392db8a-bc50-4d75-b508-b22ffaf31413.png)
> 
> Good spot! This is fixed now.
> 
> > There seem to be more issues with it, the function is receiving the webhook payload but not responding.
> 
> Are you able to provide logs?

No there were no logs and I didn't add any myself
