### ISSUE TITLE
🚀 Feature: Add WhatsApp with Vonage for Ruby 

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/templates#208]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement the WhatsApp with Vonage function in Ruby. You can look at the existing [Appwrite Functions Templates](https://github.com/appwrite/templates) in another coding language.

Your function should behave and be implemented similarly to existing WhatsApp with Vonage Node.js template.

### Tasks summary:

- [ ] Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ] Create a branch `feat-implement-whatsapp-with-vonage-ruby`
- [ ] Write code for the function in folder `ruby/whatsapp-with-vonage/`. 
- [ ] Test the function using Appwrite, **provide a video**.
- [ ] Write a `README.md` explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/whatsapp-with-vonage).
- [ ] Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy coding!**

**Comment by Whyu9-9** [comment]
Hi @gewenyu99 
I am a Software Engineer with a new knowledge to Ruby and a beginner to Open source.
Does this issue fit me? and if so, can you assign it to me and let me work on it? Thanks in advance

**Comment by Haimantika** [comment]
> Hi @gewenyu99
> I am a Software Engineer with a new knowledge to Ruby and a beginner to Open source.
> Does this issue fit me? and if so, can you assign it to me and let me work on it? Thanks in advance

Hi @Whyu9-9 have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Whyu9-9** [comment]
> > Hi @gewenyu99
> > I am a Software Engineer with a new knowledge to Ruby and a beginner to Open source.
> > Does this issue fit me? and if so, can you assign it to me and let me work on it? Thanks in advance
> 
> Hi @Whyu9-9 have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃
> 
> Notes:
> 
> Please update us with your progress every 3 days, so that we know that you are working on it. Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

Thank you! I'll keep the notes in mind.

**Comment by Haimantika** [comment]
Hi @Whyu9-9 is there any updates?

**Comment by Whyu9-9** [comment]
> Hi @Whyu9-9 is there any updates?

Hello @Haimantika 
So for my updates, i still works on the integrations with Vonage, but for the past 3 days, i'm sorry that my works got postponed because the death of my sisters and need to focus on her funeral process.
Today i will continue my works that i have left.
That's all my updates. Thank you!

**Comment by FelixFelicis555** [comment]
Hi,I want to work on this issue.Can you assign it to me ?

**Comment by Haimantika** [comment]
> > Hi @Whyu9-9 is there any updates?
> 
> Hello @Haimantika So for my updates, i still works on the integrations with Vonage, but for the past 3 days, i'm sorry that my works got postponed because the death of my sisters and need to focus on her funeral process. Today i will continue my works that i have left. That's all my updates. Thank you!

Very sorry for your loss. Please take care :)
Thanks for raising the PR, our team will review it soon

**Comment by Whyu9-9** [comment]
> > > Hi @Whyu9-9 is there any updates?
> > 
> > 
> > Hello @Haimantika So for my updates, i still works on the integrations with Vonage, but for the past 3 days, i'm sorry that my works got postponed because the death of my sisters and need to focus on her funeral process. Today i will continue my works that i have left. That's all my updates. Thank you!
> 
> Very sorry for your loss. Please take care :) Thanks for raising the PR, our team will review it soon

Thank you @Haimantika !
I already continue to work on the reviewed PR, thanks :)

**Comment by gewenyu99** [comment]
@Whyu9-9 If you need more time, we can make an exception for you 😸 

Please take more time to recover and spend time with loved ones if needed. 

Take care!

**Comment by Whyu9-9** [comment]
> @Whyu9-9 If you need more time, we can make an exception for you 😸
> 
> Please take more time to recover and spend time with loved ones if needed.
> 
> Take care!

Thank you @gewenyu99 for your attention!
I'm already good for now 👍
