### ISSUE TITLE
🚀 Feature: Add WhatsApp with Vonage for Swift 

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/templates#209]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement the WhatsApp with Vonage function in Swift. You can look at the existing [Appwrite Functions Templates](https://github.com/appwrite/templates) in another coding language.

Your function should behave and be implemented similarly to existing WhatsApp with Vonage Node.js template.

### Tasks summary:

- [ ] Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ] Create a branch `feat-implement-whatsapp-with-vonage-swift`
- [ ] Write code for the function in folder `swift/whatsapp-with-vonage/`. 
- [ ] Test the function using Appwrite, **provide a video**.
- [ ] Write a `README.md` explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/whatsapp-with-vonage).
- [ ] Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy coding!**

**Comment by RV784** [comment]
I'd like to work on this issue, please assign!

**Comment by Haimantika** [comment]
> I'd like to work on this issue, please assign!

Hi @RV784  have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:
1. Please update us with your progress every 3 days, so that we know that you are working on it.
2. Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by RV784** [comment]
I've started working on this feature today. Will keep this thread updated about the progress and ask here whenever I'll need help. @Haimantika

**Comment by soumyadeeproychowdhury** [comment]
Hey I would also love to work on this

**Comment by Haimantika** [comment]
> Hey I would also love to work on this

Hi, we are assigning issues on a first-come, first-serve basis, if the other user decides to drop off, we will assign it to you.

**Comment by RV784** [comment]
Hi, as I was going through understanding templates and Appwrite functions and I noticed a couple of things in the starter function that is already Implemented

- I was getting the following build error at my end
<img width="802" alt="Screenshot 2023-10-04 at 8 18 04 PM" src="https://github.com/appwrite/templates/assets/58266095/87094aea-7f4f-487e-82e2-9abb5c27a34a">

- This went away after changing the location of index.swift like mentioned in the below screenShot.
<img width="404" alt="Screenshot 2023-10-04 at 8 15 30 PM" src="https://github.com/appwrite/templates/assets/58266095/5b96047e-b0df-4cb1-b722-01df980d0876">

Do let me know if I'm not building it correctly in this case. I'm on Xcode-15.
@Haimantika @gewenyu99

**Comment by gewenyu99** [comment]
> Hi, as I was going through understanding templates and Appwrite functions, I noticed a couple of things in the starter function that is already Implemented
> 
> * I was getting the following build error at my end
> 
> <img alt="Screenshot 2023-10-04 at 8 18 04 PM" width="802" src="https://user-images.githubusercontent.com/58266095/272617440-87094aea-7f4f-487e-82e2-9abb5c27a34a.png">
> * This went away after changing the location of index.swift like mentioned in the below screenShot.
> 
> <img alt="Screenshot 2023-10-04 at 8 15 30 PM" width="404" src="https://user-images.githubusercontent.com/58266095/272617805-5b96047e-b0df-4cb1-b722-01df980d0876.png">
> Do let me know if I'm not building it correctly in this case. I'm on Xcode-15. @Haimantika @gewenyu99

I don't think you can build Appwrite functions locally :) They're a file depended upon by the Appwrite Functions runtimes

**Comment by RV784** [comment]
Hey, just wanted to ask that between these two approaches of saving the variables (vonage secret keys, whatsApp number etc). 
Should I go with .env file or .plist file for storing them?

First I'll go with .env file but just wanted to ask this.

**Comment by RV784** [comment]
Hi, I’m done with the Implementation of this function

Here is the progress of what I’ve done
- Created a Swift Package named ”whatsApp-with-vonage”
- Completed the implementation of all the things that I understood in the Node’s implementation of the function
- Used Swift-JWT package.
- The code is pushed in my forked repository

Things remaining
- Testing at my end

Also it would be very helpful if you could checkout the code I pushed and tell me things that can be improved.

@Haimantika @gewenyu99

**Comment by RV784** [comment]
Hi, I saw that Swift-runtime is not available in cloud.
Can you please guide me how to test it? Testing is somewhere that I got stuck.

If it goes well then I may've completed this feature implementation.

**Comment by gewenyu99** [comment]
> Hi, I saw that Swift-runtime is not available in cloud. Can you please guide me how to test it? Testing is somewhere that I got stuck.
> 
> If it goes well then I may've completed this feature implementation.

You can self-host and add functions implementation: 
https://appwrite.io/docs/advanced/self-hosting
https://appwrite.io/docs/advanced/self-hosting/functions

**Comment by RV784** [comment]
Hi, I've successfully self-hosted Appwrite locally. Will update how the functions goes after I deploy it.

**Comment by RV784** [comment]
I'm getting a little trouble with deploy manually to test.

**Comment by RV784** [comment]
I’m having a little trouble with Add deploy procedure.

- So first I’ve to package the whole swift WhatsApp with voyage function in a tar GZ file
- Then I’ve to go to my Appwrite console that is locally hosted and upload this archived file
I’m not sure where I’ve to upload my archived function file in the console.
- Also can I use CLI or is it only for cloud functions?

**Comment by Haimantika** [comment]
> I’m having a little trouble with Add deploy procedure.
> 
> * So first I’ve to package the whole swift WhatsApp with voyage function in a tar GZ file
> * Then I’ve to go to my Appwrite console that is locally hosted and upload this archived file
>   I’m not sure where I’ve to upload my archived function file in the console.
> * Also can I use CLI or is it only for cloud functions?
> 
> Edit -> Found this article (https://dev.to/appwrite/clean-your-storage-using-appwrites-swift-cloud-functions-1h4f). First will go through this then get back here if still stuck

Thanks for the update. Even after the documentation if you have any questions, you can ask us on [Discord](https://appwrite.io/discord)

**Comment by gewenyu99** [comment]
> Hey, just wanted to ask that between these two approaches of saving the variables (vonage secret keys, whatsApp number etc). Should I go with .env file or .plist file for storing them?
> 
> First I'll go with .env file but wanted to clear this doubt.

So they are passed in as environment variables through the function :)

**Comment by gewenyu99** [comment]
> I’m having a little trouble with Add deploy procedure.
> 
> * So first I’ve to package the whole swift WhatsApp with voyage function in a tar GZ file
> * Then I’ve to go to my Appwrite console that is locally hosted and upload this archived file
>   I’m not sure where I’ve to upload my archived function file in the console.
> * Also can I use CLI or is it only for cloud functions?
> 
> Edit -> Found this article (https://dev.to/appwrite/clean-your-storage-using-appwrites-swift-cloud-functions-1h4f). First will go through this then get back here if still stuck

You should be using the CLI, but it would be even better if you setup GitHub integration instead :P

**Comment by RV784** [comment]
Hi, so I manually deployed my function on self hosted Appwrite but I faced errors like shown in screenshot attached

Now most of them are syntactical but I want to ask
<img width="1180" alt="Screenshot 2023-10-21 at 11 11 10 PM" src="https://github.com/appwrite/templates/assets/58266095/731527ab-9c4d-48ef-bd77-2459ec2bca59">
 that since Xcode cannot infer the RuntimeContext/RuntimeOutput types that are mentioned in this function-Development guide -> https://appwrite.io/docs/products/functions/development#response

So can you tell in which environment should I like code the function in? Or like how do I set up this environment?

I also faced some JWT Authorisation errors but first I want to solve the above facing issues.

**Comment by RV784** [comment]
Hi, I'm facing this error while Building a function with runtime Swift-5.8. This is according to this documentation regarding development for Swift Runtime -> https://appwrite.io/docs/products/functions/development#request
<img width="1102" alt="Screenshot 2023-10-23 at 12 20 31 PM" src="https://github.com/appwrite/templates/assets/58266095/e53625c2-1cd4-401a-a2b9-5f350a492d4a">

**Comment by RV784** [comment]
So I was able to deploy the function. and I got this error no matter what I execute regardless of request method -> "An internal curl error has occurred within the executor! Error Msg: Connection reset by peer\nError Code: 500"
Currently debugging this but if you know then do help here.

**Comment by RV784** [comment]
Currently I'm trying my router's ip instead of localhost to see if it works or not.

**Comment by tessamero** [comment]
Closing issue due to inactivity and hacktoberfest being over, thank you for taking the time to be part of hacktoberfest this year :)
