### ISSUE TITLE
🚀 Feature: Add database cleaner templates

### ISSUE THREAD

**Issue by Haimantika** [appwrite/templates#226]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

### What you’re building

Your task is to implement the database cleaner template in Node.js.

Database cleaner integrates with Appwrite Databases and removes old documents from the collections older than X number of days, as configured by the **`RETENTION_PERIOD_DAYS`** environment variable. The Database cleaner should be scheduled using CRON, defaulting to running at 1:00 AM every day.

This can be useful when you have apps that receive a lot of write traffic but don’t need super long retention, such as live location updates of IoT devices or chat logs in a video game.

Your function’s implementation should be similar to other Node.js function templates in code format and style. Make sure to follow our [contributing guide](https://github.com/appwrite/templates/blob/main/CONTRIBUTING.md).

### Tasks summary:

- [ ]  Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ]  Create a branch `feat-implement-database-cleaner-node`
- [ ]  Write code for the function in folder `node/database-cleaner/`.
- [ ]  Test the function using Appwrite, **provide a video**.
- [ ]  Write a `README.md` explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/whatsapp-with-vonage).
- [ ]  Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy coding!**

**Comment by dishwasher-detergent** [comment]
I'd like to work on this issue. :)

**Comment by Haimantika** [comment]
> I'd like to work on this issue. :)

Hi @dishwasher-detergent  have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by dishwasher-detergent** [comment]
Should this be taking in the collection you are wanting to clean via the environment variables or should this just clean all collections in a project?

**Comment by Haimantika** [comment]
> Are we wanting to explicitly tell it what collection to clean based on an environment variable, or are we wanting this to just clean all collections in a project?

As the description says, we want it to clean the collections

**Comment by Gilbishkosma** [comment]
hi @Haimantika , i would like to work on this in case @dishwasher-detergent  drops.

**Comment by hdhaliwa** [comment]
@Haimantika I would to contribute for this feature.

**Comment by dishwasher-detergent** [comment]
> @Haimantika I would to contribute for this feature.

There is already an approved PR out for this.
