### ISSUE TITLE
🚀 Feature: Add storage cleaner templates

### ISSUE THREAD

**Issue by Haimantika** [appwrite/templates#227]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

### What you’re building

Your task is to implement the storage cleaner template in Node.js.

Storage cleaner integrates with Appwrite Storage and removes all files from the buckets older than X number of days, as configured by the **`RETENTION_PERIOD_DAYS`** environment variable. The Storage cleaner should be scheduled using CRON, defaulting to running at 1:00 AM daily.

This could be used in services like PDF converters and caption generators, where file retention is periodic with high number of uploads.

Your function’s implementation should be similar to other Node.js function templates in code format and style. Make sure to follow our [contributing guide](https://github.com/appwrite/templates/blob/main/CONTRIBUTING.md).

### Tasks summary:

- [ ]  Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ]  Create a branch `feat-implement-storage-cleaner-node`
- [ ]  Write code for the function in folder `node/storage-cleaner/`.
- [ ]  Test the function using Appwrite, **provide a video**.
- [ ]  Write a `README.md` explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/whatsapp-with-vonage).
- [ ]  Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy coding!**

**Comment by mbos2** [comment]
Can I work on this one?

**Comment by Haimantika** [comment]
> Can I work on this one?

Hi @mbos2  have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by mbos2** [comment]
@Haimantika As it is not specified, is it okay to use Typescript here?

**Comment by mbos2** [comment]
@Haimantika 

> The Storage cleaner should be scheduled using CRON, defaulting to running at 1:00 AM daily.

Regarding this, is this the only way of execution that should be available or can I also add execution by RESTful URL that function provides? 

By sending time in a request that can be same or different than what is defined in RETENTION_PERIOD_DAYS environment variable.

**Comment by stnguyen90** [comment]
@mbos2 let's just stick to what's mentioned in the issue description only.

**Comment by Gilbishkosma** [comment]
hi @Haimantika  , @stnguyen90 I want to work on this if @mbos2 drops.

**Comment by mbos2** [comment]
I won't drop, no worries. 

It is half way done, but still need to finish it up. 

Then test properly. 

Stress test. 

It will take couple of days @Gilbishkosma

**Comment by mbos2** [comment]
Currently in testing phase 
Along with fixing minor code issues

**Comment by mbos2** [comment]
Hi. 

Due to business trip I won't make this one, unfortunatelly. 
My appologies. 

Can you please reassign the issue to somebody else? 

Thanks.

@Haimantika

**Comment by Tushar98644** [comment]
@Haimantika can i take up the issue ?

**Comment by Haimantika** [comment]
> hi @Haimantika , @stnguyen90 I want to work on this if @mbos2 drops.

Hi, are you still interested to work on it?

**Comment by Gilbishkosma** [comment]
> > hi @Haimantika , @stnguyen90 I want to work on this if @mbos2 drops.
> 
> Hi, are you still interested to work on it?

@Haimantika yes, I would love to work on this.

**Comment by Kunal-Ladhani** [comment]
Hi would love to work on the issue

**Comment by Haimantika** [comment]
> > > hi @Haimantika , @stnguyen90 I want to work on this if @mbos2 drops.
> > 
> > 
> > Hi, are you still interested to work on it?
> 
> @Haimantika yes, I would love to work on this.

Assigned. Please update us with your progress every 3 days, so that we know that you are still working on it.

**Comment by Gilbishkosma** [comment]
Sure, thanks for assigning this to me .

**Comment by Haimantika** [comment]
Hi @Kunal-Ladhani @Tushar98644 we are assigning issues on a first-come, first-serve basis. The issues will go to you, only if the assigned user decides to drop

**Comment by drraghavendra** [comment]
Hi @Haimantika pleaseassign the issue to me

**Comment by Gilbishkosma** [comment]
@Haimantika I have raised a PR for this issue https://github.com/appwrite/templates/pull/242

**Comment by Gilbishkosma** [comment]
@Haimantika the PR #242  related to this issue is merged, we can close the issue.
