### ISSUE TITLE
🚀 Feature: Add events to Plausible templates

### ISSUE THREAD

**Issue by Haimantika** [appwrite/templates#229]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

### What you’re building

Your task is to implement the events to Plausible in Node.js.

You will implement a function that reports Appwrite events to Plausible using their [Events API](https://plausible.io/docs/events-api). This function will be triggered by configured Appwrite events and report these events to Plausible’s events API.

Your function’s implementation should be similar to other Node.js function templates in code format and style. Make sure to follow our [contributing guide](https://github.com/appwrite/templates/blob/main/CONTRIBUTING.md).

### Tasks summary:

- [ ]  Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ]  Create a branch `feat-events-to-plausible-node`
- [ ]  Write code for the function in folder `node/events-to-plausible/`.
- [ ]  Test the function using Appwrite, **provide a video**.
- [ ]  Write a `README.md` explaining what the function does, how to use it, and **customize it**. Here is [an example](https://github.com/appwrite/templates/tree/main/node/whatsapp-with-vonage)
- [ ]  Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy coding!**

**Comment by ManasMadan** [comment]
Hi Please assign this issue to me

**Comment by Haimantika** [comment]
> Hi Please assign this issue to me

Hi, I have already assigned one issue to you and we are assigning a maximum of two issues per person. Do you have the bandwidth to contribute to both?

**Comment by khushi2502** [comment]
Hey, I am ready to work on this issue. Please assign it to me.

**Comment by codewithinfiver** [comment]
I would like to work on this. Can you please assign it to me?

**Comment by omzi** [comment]
Hello @Haimantika. Kindly assign this issue to me as it's free currently :).

**Comment by Haimantika** [comment]
> Hey, I am ready to work on this issue. Please assign it to me.

Hi, assigning the issue to you. Remember to update us every 3 days, and you can ask your queries on [Discord](https://appwrite.io/discord)

**Comment by Haimantika** [comment]
Hi @codewithinfiver and @omzi we are assigning issues on a first-come, first-serve basis. If the other user gets idle, we will assign it to you.

**Comment by DanonymousCoder** [comment]
Hi @Haimantika Can you assign this issue to me

**Comment by Haimantika** [comment]
> Hi @Haimantika Can you assign this issue to me

Hi @khushi2502 is working on it, and we are assigning issues on a first-come, first serve basis.

**Comment by Haimantika** [comment]
Also @khushi2502 if there are any doubts, do not hesitate reaching out to us :)

**Comment by khushi2502** [comment]
Sure, I have started working on it now and its going quite well :)

**Comment by Haimantika** [comment]
> Sure, I have started working on it now and its going quite well :)

Hi @khushi2502 it has been 5 days without an update. Are you working on it? If not, we will be reassigning the issue to the next person soon.

**Comment by Haimantika** [comment]
> Hey I have been working on it. I'm just facing some issues with the testing step. Will be figuring it out soon.

Maybe you can raise a PR? Our reviewers can take a look + feel free to ask us questions on [Discord](https://appwrite.io/discord)

**Comment by khushi2502** [comment]
Hi @Haimantika you can assign this issue t the next user as I am not able to resolve my error :(

**Comment by HrithikSampson** [comment]
Hi @Haimantika , can I work on this issue

**Comment by tessamero** [comment]
Closing issue due to inactivity and hacktoberfest being over, thank you for taking the time to be part of hacktoberfest this year :)
