### ISSUE TITLE
🚀 Feature: Add events to Google Analytics templates

### ISSUE THREAD

**Issue by Haimantika** [appwrite/templates#230]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

### What you’re building

Your task is to implement the events to Google Analytics in Node.js.

You will implement a function that reports Appwrite events to Google Analytics. This function will be triggered by configured Appwrite events and report these events to Google Analytics..

Your function’s implementation should be similar to other Node.js function templates in code format and style. Make sure to follow our [contributing guide](https://github.com/appwrite/templates/blob/main/CONTRIBUTING.md).

### Tasks summary:

- [ ]  Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ]  Create a branch `feat-events-to-ga-node`
- [ ]  Write code for the function in folder `node/events-to-ga/`.
- [ ]  Test the function using Appwrite, **provide a video**.
- [ ]  Write a `README.md` explaining what the function does, how to use it, and **customize it**. Here is [an example](https://github.com/appwrite/templates/tree/main/node/whatsapp-with-vonage).
- [ ]  Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy coding!**

**Comment by ManasMadan** [comment]
Hi Please assign this issue to me

**Comment by HrithikSampson** [comment]
Hi Please assign this issue to me

**Comment by Haimantika** [comment]
> Hi Please assign this issue to me

Hi, I have already assigned one issue to you, will you have the bandwidth to contribute to both?

**Comment by khushi2502** [comment]
Hello, Please assign this issue to me.

**Comment by HimanshuTembhe** [comment]
Can you assign this issue to me ?

**Comment by Haimantika** [comment]
> Hi Please assign this issue to me.

Assigned it to you. Please update us every 3 with the status of the issue and for any queries, you can ask us on [Discord](https://appwrite.io/discord)

**Comment by HrithikSampson** [comment]
Thanks @Haimantika

**Comment by shaurya-jain23** [comment]
Can you please assign it to me.

**Comment by HrithikSampson** [comment]
Hi @Haimantika I am working on this issue I have figured out the event subscription and passing the data I still need 1 more day to test it

**Comment by HrithikSampson** [comment]
Hi @Haimantika can i submit it with events getting reported as the event name,
 or All User / Team events will be one event and params will be different on whatever is after the fullstop as each param key's value. Or I could take a list of event regex and find for each event which is the longest regex it matches and register that as the event

**Comment by HrithikSampson** [comment]
Hi @Haimantika , I have created a pull request

**Comment by Albin-mca** [comment]
I would like to work on this. Can you please assign it to me?🤩

**Comment by tessamero** [comment]
Closing issue due to inactivity, thank you for taking the time to be part of hacktoberfest this year :)
