### ISSUE TITLE
🚀 Feature: Add Email Contact Form Function for Java

### ISSUE THREAD

**Issue by Haimantika** [appwrite/templates#78]
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement the Email Contact Form function in Java. You can look at the existing [Appwrite Functions Templates](https://github.com/appwrite/templates) in another coding language.

Your function should behave and be implemented similarly to existing Email Contact Form Node.js template.

### Tasks summary:

- [ ] Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ] Create a branch `feat-implement-email-contact-form-java`
- [ ] Write code for the function in folder `java/email-contact-form/`. 
- [ ] Test the function using Appwrite, **provide a video**.
- [ ] Write a `README.md` explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/email-contact-form).
- [ ] Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by PalaniappanC** [comment]
Hi @Haimantika Can you please assign this issue to my name. I would like to work on this issue

**Comment by PalaniappanC** [comment]
Hi @Haimantika @christyjacob4  Can you please assign this issue to my name. I would like to work on this issue and started the analysis.

**Comment by PalaniappanC** [comment]
Hi @gewenyu99 @Haimantika @christyjacob4 Can you please assign this issue to my name. I would like to work on this issue and started the analysis.

**Comment by loks0n** [comment]
Hi @PalaniappanC, I've assigned the issue to you! Happy Hacktoberfest 🎃!

Notes:
- Please update us with your progress every 3 days, so that we know you are working on it.
- Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by PalaniappanC** [comment]
Hi @geeky-decoder I am working on this issue..

**Comment by geeky-decoder** [comment]
@loks0n @Haimantika Can 1 issue be worked upon by only 1 contributor. If not than do assign to me. Thanks!

**Comment by Haimantika** [comment]
> @loks0n @Haimantika Can 1 issue be worked upon by only 1 contributor. If not than please do assign to me as well. Thanks!

Hi, yes. Only one person at a time, and we assigning on a first-come first-serve basis. If the other user decides to drop, that’s when we assign it to you.

**Comment by geeky-decoder** [comment]
@Haimantika Thanks for the clarification. Much Appreciated! Do assign me if in case any blocker arises. Thanks!

**Comment by PalaniappanC** [comment]
Hi @gewenyu99 @Haimantika @christyjacob4 @loks0n 

I have started working on this Feature. 

Tasks summary:
 [] Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
 [] Create a branch feat-implement-email-contact-form-java
 [] Write code for the function in folder java/email-contact-form/.
 [] Test the function using Appwrite, provide a video.
 [] Write a README.md explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/email-contact-form).
 [] Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

**Comment by Haimantika** [comment]
Hi @PalaniappanC do you have an update?

**Comment by PalaniappanC** [comment]
Hi @Haimantika  I have written the code for email-contact-form. Have to test it by deploying the function on the self host appwrite instance

**Comment by Shunux-Stuxnet** [comment]
Hi @Haimantika Can you assign this issue to me, i would like to work on this.

**Comment by Haimantika** [comment]
> Hi @Haimantika Can you assign this issue to me, i would like to work on this.

Hi, this issue has already been worked on :)

**Comment by PalaniappanC** [comment]
Hi @Haimantika this PR is waiting to be reviewed and I can't join the PR review party as the timing doesn't suite for me. Please review this PR.
